// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'BiddingModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BiddingModel _$BiddingModelFromJson(Map<String, dynamic> json) => BiddingModel(
      json['product_idx'] as int?,
      json['product_user_idx'] as int?,
      json['product_state'] as int?,
      json['product_manufacturer'] as String?,
      json['product_model'] as String?,
      json['product_year'] as String?,
      json['product_mileage'] as String?,
      json['product_image'] as String?,
      json['product_detail'] as String?,
      json['product_town_idx'] as int?,
      json['product_endtime'] as String?,
      json['city_name'] as String?,
      json['town_name'] as String?,
      json['buy_idx'] as int?,
      json['buy_product_idx'] as int?,
      json['buy_dealer_idx'] as int?,
      json['buy_price'] as int?,
      json['buy_state'] as int?,
      json['buy_createtime'] as String?,
      json['user_idx'] as int?,
      json['user_id'] as String?,
      json['user_name'] as String?,
      json['user_phone'] as String?,
      json['user_alarm'] as int?,
      json['user_token'] as String?,
      json['pay_idx'] as int?,
      json['pay_buy_idx'] as int?,
      json['pay_price'] as int?,
      json['pay_detail'] as String?,
      json['pay_state'] as int?,
      json['dealer_id'] as String?,
      json['dealer_name'] as String?,
      json['dealer_phone'] as String?,
    );

Map<String, dynamic> _$BiddingModelToJson(BiddingModel instance) =>
    <String, dynamic>{
      'product_idx': instance.product_idx,
      'product_user_idx': instance.product_user_idx,
      'product_state': instance.product_state,
      'product_manufacturer': instance.product_manufacturer,
      'product_model': instance.product_model,
      'product_year': instance.product_year,
      'product_mileage': instance.product_mileage,
      'product_image': instance.product_image,
      'product_detail': instance.product_detail,
      'product_town_idx': instance.product_town_idx,
      'product_endtime': instance.product_endtime,
      'city_name': instance.city_name,
      'town_name': instance.town_name,
      'buy_idx': instance.buy_idx,
      'buy_product_idx': instance.buy_product_idx,
      'buy_dealer_idx': instance.buy_dealer_idx,
      'buy_price': instance.buy_price,
      'buy_state': instance.buy_state,
      'buy_createtime': instance.buy_createtime,
      'user_idx': instance.user_idx,
      'user_id': instance.user_id,
      'user_name': instance.user_name,
      'user_phone': instance.user_phone,
      'user_alarm': instance.user_alarm,
      'user_token': instance.user_token,
      'pay_idx': instance.pay_idx,
      'pay_buy_idx': instance.pay_buy_idx,
      'pay_price': instance.pay_price,
      'pay_detail': instance.pay_detail,
      'pay_state': instance.pay_state,
      'dealer_id': instance.dealer_id,
      'dealer_name': instance.dealer_name,
      'dealer_phone': instance.dealer_phone,
    };
